### ISSUE TITLE
Doesn't work on Ruby 1.9.2

### ISSUE THREAD

**Issue by clbustos** [clbustos/extendmatrix#1]
The new methods on Matrix conflict with extension. Now, three test doesn't pass.

1)
TypeError in 'Matrix class extension: row2matrix'
can't convert Range into Integer
spec/extendmatrix_spec.rb:213:in `block (2 levels) in <top (required)>'

2)
NoMethodError in 'Matrix class extension: houseQR '
undefined method `size' for nil:NilClass
spec/extendmatrix_spec.rb:282:in`block (2 levels) in <top (required)>'

3)
NoMethodError in 'Matrix class extension: houseR '
undefined method `size' for nil:NilClass
spec/extendmatrix_spec.rb:296:in`block (2 levels) in <top (required)>'

4)
NoMethodError in 'Matrix class extension: bidiagonalization'
undefined method `size' for nil:NilClass
spec/extendmatrix_spec.rb:306:in`block (2 levels) in <top (required)>'

5)
NoMethodError in 'Matrix class extension: hessenbergQR '
undefined method `size' for nil:NilClass
spec/extendmatrix_spec.rb:331:in`block (2 levels) in <top (required)>'

6)
NoMethodError in 'Matrix class extension: realSchur'
undefined method `size' for nil:NilClass
spec/extendmatrix_spec.rb:351:in`block (2 levels) in <top (required)>'

Finished in 0.08513933899999999 seconds

**Comment by clbustos** [comment]
Resolved on 0.2.2
